# Generated by Django 4.1.2 on 2022-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_contactbook_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
