# Generated by Django 4.1.2 on 2022-10-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_contactbook_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
